### PR TITLE
Check before overwriting buffer

### PR DESCRIPTION
**Pull request by ineiti**
This PR adds a verification before overwriting the 'Buffer' global.

### CODE REVIEW

**Review by ynizon — APPROVED** [review]
perfect

**Comment by ineiti** [comment]
@ynizon - you're also using `stackblitz` and have projects that use asn1.js fail?

**Comment by ynizon** [comment]
Yes, i need this fix 👍 thanks

**Comment by ineiti** [comment]
Let's hope @indutny picks it up ;) I didn't try to fork it and then reference it in stackblitz - I'm not sure how good stackblitz is when replacing packages...

**Pull request closed without merging**
