### PR TITLE
Update asn1.js

### PR DESCRIPTION
**Pull request by guybedford**
These also need to be updated to iron out the bn.js 0.15 dependency.

### CODE REVIEW

**Comment by guybedford** [comment]
And if this becomes a minor upgrade, https://github.com/calvinmetcalf/parse-asn1/blob/master/package.json#L17 will also need to be updated.

**Comment by indutny** [comment]
Fixed now please update your deps ;)

**Comment by guybedford** [comment]
Oh man, this is going to take a while to push up the tree:

```
       npm:asn1.js@0.6.7
         bn.js 0.15.2 (^0.15.0)
     
       npm:browserify-rsa@1.1.0
         bn.js 0.16.1 (^0.16.0)
     
       npm:browserify-sign@2.7.1
         bn.js 0.16.1 (^0.16.0)
     
       npm:browserify-sign@2.7.2
         bn.js 0.16.1 (^0.16.0)
     
       npm:create-ecdh@1.0.1
         bn.js 0.16.1 (^0.16.0)
     
       npm:diffie-hellman@2.2.2
         bn.js 0.16.1 (^0.16.0)
     
       npm:elliptic@0.15.17
         bn.js 0.16.1 (^0.16.0)
     
       npm:miller-rabin@1.1.4
         bn.js 0.16.1 (^0.16.0)
     
       npm:miller-rabin@1.1.5
         bn.js 1.0.0 (^1.0.0)
     
       npm:public-encrypt@1.1.0
         bn.js 0.16.1 (^0.16.0)
```

Will see what I can do...

**Comment by guybedford** [comment]
Ok, so the steps I've done are:

* https://github.com/calvinmetcalf/parse-asn1/pull/2
* https://github.com/calvinmetcalf/browserify-rsa/pull/1
* https://github.com/calvinmetcalf/browserify-sign/pull/6
* https://github.com/calvinmetcalf/createECDH/pull/2
* https://github.com/calvinmetcalf/diffie-hellman/pull/9
* https://github.com/calvinmetcalf/publicEncrypt/pull/2

There will be more to move up the other layers too I expect, since there are exact version locks in https://github.com/dominictarr/crypto-browserify/blob/master/package.json and another project I think.

**Comment by indutny** [comment]
Thank you!

**Comment by calvinmetcalf** [comment]
well good thing every single one of these are mine and I am not on my honey moon this time

**Comment by guybedford** [comment]
Thanks for looking into it so quickly.

**Comment by indutny** [comment]
Yay! @calvinmetcalf you rock!

**Pull request closed without merging**
