### PR TITLE
Add .npmignore files to avoid packaging unneeded files

### PR DESCRIPTION
**Pull request by marco-c**
The main package shouldn't need to include the tests and the packages under rfc/.
The rfc packages only need not to include the tests.

### CODE REVIEW

**Comment by fanatid** [comment]
@marco-c OOI, why you added `rfc/2560/.npmignore` and `rfc/5280/.npmignore`? `rfc` in main `.npmignore` not work?

**Comment by marco-c** [comment]
@fanatid they are separate packages, they're published separately from the main package.

**Comment by fanatid** [comment]
oh, really, sorry..

**Comment by indutny** [comment]
Landed in c5babea, sorry for delay!

**Comment by marco-c** [comment]
Could you publish a new minor release?

**Comment by indutny** [comment]
Done!

**Pull request closed without merging**
