### PR TITLE
Remove cyclic dependencies

### LINKED ISSUE #98: base

### PR DESCRIPTION
**Pull request by lordvlad**
closes #98 and possibly #100

### CODE REVIEW

**Comment by lordvlad** [comment]
@indutny bump.

is this project alive? I'd love to share responsibility/ownership if that's something you're willing to do

**Comment by cdata** [comment]
@indutny friendly ping from an interested (transitive) user of this library

**Comment by indutny** [comment]
Landed in a85daf4, and released in 5.2.0 . Terribly sorry for the long delay.

**Comment by indutny** [comment]
Thank you!

**Pull request closed without merging**
