### PR TITLE
Fix call to def()

### PR DESCRIPTION
**Pull request by novemberborn**

### CODE REVIEW

**Comment by indutny** [comment]
Hello!

Thank you so much for contributing this change. May I ask you if you could be interested in contributing a test case to reproduce this problem?

Thank you!

**Comment by novemberborn** [comment]
I suppose I could dig up the certificate this crashed for, but even then the test would be "this certificate can be decoded". The tests are pretty basic at the moment and this PR simply fixes a bad function call.

**Comment by felix** [comment]
I think this should be merged, I made a typo.

**Comment by indutny** [comment]
Alright, let's land it.

**Comment by indutny** [comment]
Landed in ae90349. Thank you!

**Comment by indutny** [comment]
Released updated module too.

**Pull request closed without merging**
